- name: Copy frontend file and install nginx
  template:
    src: templates/frontend.j2
    dest: "/tmp/frontend.txt"
  tasks:
    - name: "apt-get update"
      apt: 
        update_cache: yes
        cache_valid_time: 3600
    - name: "install nginx"
      apt:
        name: nginx
        state: latest
      notify: restart nginx