---
# tasks file for network
- name: Créer un réseau virtuel Azure
  azure.azcollection.azure_rm_virtualnetwork:
    name: "{{ vnet_name }}"
    resource_group: "{{ resource_group_name }}"
    location: "{{ resource_group_location }}"
    address_prefixes: "{{ address_space }}"

- name: Créer des sous-réseaux dans le VNet
  azure.azcollection.azure_rm_subnet:
    name: "{{ item.name }}"
    resource_group: "{{ resource_group_name }}"
    virtual_network: "{{ vnet_name }}"
    address_prefix: "{{ item.prefix }}"
  loop: "{{ subnets }}"